name: "Check Pull Request"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: PR Title Verify
        uses: satvik-s/pr-title-check@1.1.0
        with:
          pattern: '^(feat|chore|doc|fix|security|refactor|test|wip):[ ]?.{3,}$'
